swagger: "2.0"
info:
  version: "1.0.0"
  title: "Add Calendar Entry"
tags:
  - name: " Calendar"
    description: "Operations related to the "
paths:
  /api/calendar/add:
    post:
      tags:
        - "Calendar"
      summary: "Add a new calendar entry for the authenticated user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "user_id"
          type: "string"
          required: true
          description: "User ID"
        - in: "body"
          name: "body"
          description: "New calendar entry details"
          required: true
          schema:
            $ref: "#/definitions/CalendarRequest"
      responses:
        201:
          description: "Entry added successfully"
        400:
          description: "Invalid entry data"
