swagger: "2.0"
info:
  title: "Calendar API - Get All Entries"
  description: "Get all calendar entries for the authenticated user"
  version: "1.0"
paths:
  /api/calendar:
    get:
      tags:
        - "Calendar"
      summary: "Get all calendar entries for the authenticated user"
      security:
        - BearerAuth: []
      produces:
        - "application/json"
      responses:
        200:
          description: "List of calendar entries."
          schema:
            $ref: "calendar_response.yml"
        401:
          description: "Unauthorized."
