swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Logout"
tags:
  - name: " User"
    description: "Operations related to the "
paths:
  /api/logout:
    post:
      tags:
        - "User"
      summary: "User logout"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Logged out successfully"
