swagger: "2.0"
info:
  version: "1.0.0"
  title: "User Registration"
tags:
  - name: " User"
    description: "Operations related to the "
paths:
  /api/register:
    post:
      tags:
        - "User"
      summary: "User registration"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User registration details"
          required: true
          schema:
            $ref: "#/definitions/UserCreateRequest"
      responses:
        201:
          description: "Registered successfully"
        400:
          description: "Bad Request"
