swagger: "2.0"
info:
  version: "1.0.0"
  title: "Edit Calendar Entry"
tags:
  - name: " Calendar"
    description: "Operations related to the "
paths:
  /api/calendar/update/{entry_id}:
    put:
      tags:
        - "Calendar"
      summary: "Update a calendar entry for the authenticated user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "user_id"
          type: "string"
          required: true
          description: "User ID"
        - in: "path"
          name: "entry_id"
          type: "string"
          required: true
          description: "ID of the calendar entry"
        - in: "body"
          name: "body"
          description: "Updated calendar entry details"
          required: true
