swagger: "2.0"
info:
  title: "Calendar API - User Login"
  description: "Authenticate a user and generate a token"
  version: "1.0"
paths:
  /api/login:
    post:
      tags:
        - "Calendar"
      summary: "Authenticate a user and generate a token"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "user_login_request.yml"
      responses:
        200:
          description: "Successful login. Returns a JWT token."
          schema:
            $ref: "login_response.yml"
        401:
          description: "Unauthorized. Invalid credentials."
